AlignParameters:
  Enabled: false

Encoding:
  Enabled: false

LineLength:
  Max: 200

HashSyntax:
  EnforcedStyle: hash_rockets

MethodLength:
  Max: 35

CyclomaticComplexity:
  Max: 9

ParameterLists:
  Enabled: false

StringLiterals:
  Enabled: false

SpaceInsideBrackets:
  Enabled: false

#Some recipes have a valid reason to do so, see bprobe for example
RescueException:
  Enabled: false

AccessorMethodName:
  Enabled: false

#I dont want to separate port numbers with underscores.
NumericLiterals:
  Enabled: false





# Temp disabled rules below. Remove them on at a time, and refactor the
# Cookbooks.

RedundantSelf:
  Enabled: false

Void:
  Enabled: false

FavorSprintf:
  Enabled: false

ModuleFunction:
  Enabled: false

PredicateName:
  Enabled: false

Syntax:
  Enabled: false

ParenthesesAsGroupedExpression:
  Enabled: false

RedundantBegin:
  Enabled: false

Documentation:
  Enabled: false

UselessAssignment:
  Enabled: false

WordArray:
  Enabled: false

FavorUnlessOverNegatedIf:
  Enabled: false

IfUnlessModifier:
  Enabled: false
